version: '3'

services:
  php:
    container_name: WEB_SERVER
    build: ./php
    links: 
      - mariadb:db
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
    depends_on:
      - mariadb

  mariadb:
    container_name: DB_SERVER
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./sql/sait.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "3306:3306"
    env_file:
      - .env

  phpmyadmin:
    container_name: MYADMIN
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - "8765:80"
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php.ini:/etc/php/7.0/apache2/php.ini
    env_file:
      - .env
    depends_on:
      - mariadb
